import { Event, HandlerDetails } from "electron";
import ElectronLogger from "../vendor/ElectronLogger.ts";
import ElectronStore from "../vendor/ElectronStore.ts";
import MainWindow from "../windows/MainWindow.ts";
import BrowserWindow from "../windows/BrowserWindow.ts";
import VideoRepository from "../repository/VideoRepository.ts";
import { SniffingHelper, SourceParams } from "./SniffingHelperService.ts";
export default class WebviewService {
    private readonly mainWindow;
    private readonly logger;
    private readonly browserWindow;
    private readonly store;
    private readonly videoRepository;
    private readonly sniffingHelper;
    private view;
    private blocker?;
    private defaultSession;
    private viewShow;
    constructor(mainWindow: MainWindow, logger: ElectronLogger, browserWindow: BrowserWindow, store: ElectronStore, videoRepository: VideoRepository, sniffingHelper: SniffingHelper);
    init(): Promise<void>;
    onWillNavigate: (e: Event, url: string) => void;
    onDomReady: () => void;
    onDidNavigate: () => Promise<void>;
    onDidFailLoad: (e: Event, code: number, desc: string) => void;
    onDidNavigateInPage: () => void;
    onOpenNewWindow: ({ url }: HandlerDetails) => {
        action: "deny";
    };
    onSource: (item: SourceParams) => Promise<void>;
    getPageInfo(): {
        title: string;
        url: string;
    };
    getBounds(): Electron.Rectangle;
    setBounds(bounds: Electron.Rectangle): void;
    setBackgroundColor(color: string): void;
    show(): void;
    hide(): void;
    loadURL(url: string): void;
    goBack(): Promise<boolean>;
    reload(): Promise<void>;
    goHome(): Promise<void>;
    get window(): Electron.CrossProcessExports.BrowserWindow;
    private get session();
    private enableProxy;
    private disableProxy;
    setProxy(useProxy: boolean, proxy: string): void;
    setBlocking(enableBlocking: boolean): void;
    initBlocker(): Promise<void>;
    private enableBlocking;
    private disableBlocking;
    setAudioMuted(audioMuted?: boolean): void;
    setUserAgent(isMobile?: boolean): void;
    captureView(): Promise<Electron.NativeImage | null>;
    sendToWindow(channel: string, ...args: unknown[]): void;
    destroyView(): void;
    clearCache(): Promise<void>;
    setDefaultSession(isPrivacy?: boolean, init?: boolean): void;
}
