import { IpcMainEvent } from "electron";
import { Favorite } from "../entity/Favorite.ts";
import { AppStore, EnvPath } from "../main.ts";
import { type Controller } from "../interfaces.ts";
import MainWindow from "../windows/MainWindow.ts";
import BrowserWindow from "../windows/BrowserWindow.ts";
import ElectronStore from "../vendor/ElectronStore.ts";
import WebviewService from "../services/WebviewService.ts";
import FavoriteRepository from "../repository/FavoriteRepository.ts";
import VideoRepository from "../repository/VideoRepository.ts";
import ConversionRepository from "../repository/ConversionRepository.ts";
import ElectronLogger from "../vendor/ElectronLogger.ts";
import ElectronUpdater from "../vendor/ElectronUpdater.ts";
export default class HomeController implements Controller {
    private readonly store;
    private readonly favoriteRepository;
    private readonly mainWindow;
    private readonly videoRepository;
    private readonly browserWindow;
    private readonly webviewService;
    private readonly conversionRepository;
    private readonly logger;
    private readonly updater;
    private sharedState;
    constructor(store: ElectronStore, favoriteRepository: FavoriteRepository, mainWindow: MainWindow, videoRepository: VideoRepository, browserWindow: BrowserWindow, webviewService: WebviewService, conversionRepository: ConversionRepository, logger: ElectronLogger, updater: ElectronUpdater);
    getEnvPath(): Promise<EnvPath>;
    getFavorites(): Promise<Favorite[]>;
    addFavorite(e: IpcMainEvent, favorite: Favorite): Promise<Favorite>;
    removeFavorite(e: IpcMainEvent, id: number): Promise<void>;
    getAppStore(): AppStore;
    onFavoriteItemContextMenu(e: IpcMainEvent, id: number): Promise<void>;
    selectDownloadDir(): Promise<string>;
    setAppStore(e: IpcMainEvent, key: keyof AppStore, val: any): Promise<void>;
    openDir(e: IpcMainEvent, dir: string): Promise<void>;
    openUrl(e: IpcMainEvent, url: string): Promise<void>;
    downloadListContextMenu(e: IpcMainEvent, id: number): Promise<void>;
    convertToAudio(e: IpcMainEvent, id: number): Promise<void>;
    showBrowserWindow(): Promise<void>;
    combineToHomePage(): Promise<void>;
    getLocalIp(): Promise<string>;
    getSharedState(): Promise<Record<string, unknown>>;
    setSharedState(event: IpcMainEvent, state: any): Promise<void>;
    getDownloadLog(event: IpcMainEvent, id: number): Promise<string>;
    selectFile(): Promise<string>;
    getMachineId(): Promise<string>;
    exportFavorites(): Promise<undefined>;
    importFavorites(): Promise<undefined>;
    checkUpdate(): Promise<void>;
    startUpdate(): Promise<void>;
    installUpdate(): Promise<void>;
    exportDownloadList(): Promise<undefined>;
    getVideoFolders(): Promise<string[]>;
}
