export declare function getLocalIP(): string;
declare function fetchWrapper(url: string): Promise<import("node-fetch").Response>;
export declare function noop(): void;
export { sleep, formatHeaders } from "./utils.ts";
export * from "./variables.ts";
export { on, handle } from "./decorator.ts";
export { convertToAudio } from "./ffmpeg.ts";
export { fetchWrapper as fetch };
export { fileExists } from "./file.ts";
export { videoPattern } from "./video.ts";
export { urlCache } from "./cache.ts";
